databases:
  - name: mysite
    databaseName: hello_app_rails
    user: hello_app_rails

services:
  - type: web
    name: hello_app
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hello_app_rails
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false